/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __IMPLICITHEATEQUATION_H_
#define __IMPLICITHEATEQUATION_H_

#include <fstream>
#include <iomanip>
#include <type_traits>
#include <limits>
#include <utility>
#include <cmath>
#include <leveldb/db.h>
#include <leveldb/write_batch.h>
#include <omp.h>
#include <cstdio>
#include "nablalib/mesh/CartesianMesh2DFactory.h"
#include "nablalib/mesh/CartesianMesh2D.h"
#include "nablalib/utils/Utils.h"
#include "nablalib/utils/Timer.h"
#include "nablalib/types/Types.h"
#include "nablalib/utils/Serializer.h"
#include "nablalib/mesh/PvdFileWriter2D.h"
#include "LinearAlgebra.h"

using namespace nablalib::mesh;
using namespace nablalib::utils;
using namespace nablalib::types;
using namespace nablalib::utils::stl;

/******************** Free functions declarations ********************/

namespace implicitheatequationfreefuncs
{
template<size_t x>
double norm(RealArray1D<x> a);
template<size_t x>
double dot(RealArray1D<x> a, RealArray1D<x> b);
double det(RealArray1D<2> a, RealArray1D<2> b);
template<size_t x>
RealArray1D<x> sumR1(RealArray1D<x> a, RealArray1D<x> b);
double minR0(double a, double b);
double sumR0(double a, double b);
double prodR0(double a, double b);
}

/******************** Module declaration ********************/

class ImplicitHeatEquation
{
	/* Don't move this object around */
	ImplicitHeatEquation(ImplicitHeatEquation &&)           = delete;
	ImplicitHeatEquation(const ImplicitHeatEquation &)      = delete;
	ImplicitHeatEquation& operator=(ImplicitHeatEquation &) = delete;

public:
	struct Options
	{
		double u0;
		double stopTime;
		int maxIterations;
		LinearAlgebra linearAlgebra;
		std::string nonRegression;

		void jsonInit(const char* jsonContent);
	};

	ImplicitHeatEquation(CartesianMesh2D* aMesh, Options& aOptions);
	~ImplicitHeatEquation();

	void simulate();
	void computeFaceLength() noexcept;
	void computeTn() noexcept;
	void computeV() noexcept;
	void initD() noexcept;
	void initTime() noexcept;
	void initXc() noexcept;
	void updateU() noexcept;
	void computeDeltaTn() noexcept;
	void computeFaceConductivity() noexcept;
	void initU() noexcept;
	void setUpTimeLoopN() noexcept;
	void computeAlphaCoeff() noexcept;
	void executeTimeLoopN() noexcept;
	void createDB(const std::string& db_name);

private:
	// Mesh and mesh variables
	CartesianMesh2D* mesh;
	size_t __attribute__((unused))nbNodes, nbCells, nbFaces, nbNeighbourCells, nbNodesOfFace, nbCellsOfFace, nbNodesOfCell;

	// User options
	Options& options;

	// Timers
	Timer globalTimer;
	Timer cpuTimer;
	Timer ioTimer;

public:
	// Global variables
	int n;
	static constexpr RealArray1D<2> vectOne = {1.0, 1.0};
	double deltat;
	double t_n;
	double t_nplus1;
	double t_n0;
	std::vector<RealArray1D<2>> X;
	std::vector<RealArray1D<2>> Xc;
	Vector u_n;
	Vector u_nplus1;
	std::vector<double> V;
	std::vector<double> D;
	std::vector<double> faceLength;
	std::vector<double> faceConductivity;
	Matrix alpha;
};

#endif
